# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RRGGo0gDWkI6tVe8zQwyiOBjC3Lh1C9k
"""

# Commented out IPython magic to ensure Python compatibility.
# from numpy._core.defchararray import count
# %%writefile data_cleaning.py
# import pandas as pd
# import matplotlib.pyplot as plt
# import seaborn as sns
# df = pd.read_csv("/content/real_estate_data.csv")
# print(df)
# sns.boxplot(x=df["Price_Lakh"]) #Create a boxplot for Price_Lakh.
# plt.show()
# 
# sns.boxplot(x=df["Area_sqft"]) #Create a boxplot for Area_sqft.
# plt.show()
# 
# q1=df["Price_Lakh"].quantile(0.25)
# q2=df["Price_Lakh"].quantile(0.75)
# 
# iqr=q2-q1
# 
# lower_b=q1-1.5*iqr
# upper_b=q2+iqr*1.5
# 
# print(df[df["Price_Lakh"]>upper_b])
# print(df[df["Price_Lakh"]<lower_b])
# print(df)
# sns.boxplot(x=df["Price_Lakh"]) #Create a boxplot for Price_Lakh.
# plt.show()
# 
# sns.boxplot(x=df["Area_sqft"]) #Create a boxplot for Area_sqft.
# plt.show()
# 
# q1=df["Price_Lakh"].quantile(0.25) #Use the IQR method to identify outliers in Price_Lakh.
# q2=df["Price_Lakh"].quantile(0.75)
# 
# iqr=q2-q1
# 
# lower_b=q1-1.5*iqr
# upper_b=q2+iqr*1.5
# 
# print(df[df["Price_Lakh"]>upper_b])
# print(df[df["Price_Lakh"]<lower_b])
# 
# print(df["City"].value_counts()) #Find how many houses are listed in each city.
# 
# df.fillna({"Owner_Type":df["Owner_Type"].mode()[0]},inplace=True) #Find the unique values in Owner_Type.
# print(df["Owner_Type"].unique())
# 
# print(df["Parking"].value_counts()) #Find the number of houses with and without parking.
# 
# df.loc[df["Parking"] == "Yes", "Parking"] = 1 #Convert Parking into numerical values:
# df.loc[df["Parking"] == "No", "Parking"] = 0
# 
# print(df["Parking"])
# 
# df["Posted_Date"]=pd.to_datetime(df["Posted_Date"])
# print(df["Posted_Date"])
# 
# df["Posted_Month"]=df["Posted_Date"].dt.month
# print(df["Posted_Month"])
# 
# df["Posted_Day"]=df["Posted_Date"].dt.day
# print(df["Posted_Day"])
# 
# df.fillna({"Price_Lakh":df["Price_Lakh"].mode()[0]},inplace=True)
# df.fillna({"Area_sqft":df["Area_sqft"].mode()[0]},inplace=True)
# df["Price_per_sqft"]=(df["Price_Lakh"]*100000)/df["Area_sqft"]
# print(df["Price_per_sqft"])
# 
# df.fillna({"Bedrooms":df["Bedrooms"].mode()[0]},inplace=True)
# df["Price_per_bedroom"] = df["Price_Lakh"] / df["Bedrooms"]
# print(df["Price_per_bedroom"])
# 
# df.fillna({"Age":df["Age"].mode()[0]},inplace=True)
# 
# df.loc[df["Age"] <= 5, "House_Age_Category"] = "New"
# 
# df.loc[(df["Age"] > 5) & (df["Age"] <= 15), "House_Age_Category"] = "Medium"
# 
# df.loc[df["Age"] > 15, "House_Age_Category"] = "Old"
# 
# print(df["House_Age_Category"])
# 
# 
# 
# 
# 
# 
# 
#